# Задачи к первой лабораторной работе

# Задача 1

In [5]:
import numpy
def matrixgenerate():
    n=int(input())
    massiv = numpy.random.random_integers(0, 20, size=(n))
    
    for i, j in enumerate(massiv):
        print("massiv[", i, "]=", j)
    return massiv
def perimetr(massiv):
    massiv=sorted(massiv, reverse=True)
    for i in range(len(massiv)-2):
        if massiv[i]<massiv[i+1]+massiv[i+2]:
            return massiv[i]+massiv[i+1]+massiv[i+2]

In [6]:
massiv=matrixgenerate()
P=perimetr(massiv)
print(P)

10
massiv[ 0 ]= 7
massiv[ 1 ]= 3
massiv[ 2 ]= 7
massiv[ 3 ]= 19
massiv[ 4 ]= 7
massiv[ 5 ]= 20
massiv[ 6 ]= 19
massiv[ 7 ]= 9
massiv[ 8 ]= 2
massiv[ 9 ]= 3
58


<ipython-input-5-9518fbb5a8ef>:4: DeprecationWarning: This function is deprecated. Please call randint(0, 20 + 1) instead
  massiv = numpy.random.random_integers(0, 20, size=(n))


# Задача 2

In [ ]:
def check(a,b):
    one=str(a)+str(b)
    two=str(b)+str(a)
    if int(one)>int(two):
        return True
    else:
        return False
    
def shell(massline):
    length=len(massline)
    l=length
    while l>0:
        for i in range(length-l):
            j=i
            while j>=0 and check(massline[j+l], massline[j]):
                massline[j], massline[j+l]=massline[j+l], massline[j]
                j=j-l
        l=int(l/2)
    strr=""
    for i in range(len(massline)):
        strr=strr+" "+str(massline[i])
    return strr

mas1=[8308,8308,830]
mas2=[99991,9]
mas3=[3,30,34,5,9]
print(shell(mas1))
print(shell(mas2))
print(shell(mas3))

# Задача 3

In [8]:
import numpy
m, n= map(int, input('Введите m и n:').split(' '))
massiv = numpy.random.random_integers(0, 20, size=(m, n))
print(massiv)
for i in range(0,m):
    for j in range(0,n):
        l=j
        k=i
        while k<m and l<n:
            if massiv[i][j]>massiv[k][l]:
                print ("заменяет " , massiv[k][l] ," на " , massiv[i][j] )
                massiv[i][j], massiv[k][l]=massiv[k][l], massiv[i][j]
            k=k+1
            l=l+1
print("\n")
print(massiv)

Введите m и n:5 4
[[15  1 20  0]
 [12 16 13 17]
 [17 20 19 19]
 [20 10  0 10]
 [ 6  1  0 15]]
заменяет  10  на  15
заменяет  17  на  20
заменяет  0  на  12
заменяет  15  на  16
заменяет  10  на  17
заменяет  0  на  10
заменяет  12  на  20
заменяет  16  на  19
заменяет  1  на  20
заменяет  10  на  17
заменяет  15  на  20


[[10  1 17  0]
 [ 0 15 13 20]
 [ 0 12 16 19]
 [ 1 10 15 19]
 [ 6 20 17 20]]


<ipython-input-8-5a0ebf00e0be>:3: DeprecationWarning: This function is deprecated. Please call randint(0, 20 + 1) instead
  massiv = numpy.random.random_integers(0, 20, size=(m, n))
